version: 1.38.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: $(appveyor_repo_commit)
before_build:
- ps: '[System.IO.File]::AppendAllText("C:\Windows\System32\drivers\etc\hosts", "`n93.184.221.200  api.nuget.org")'
- cmd: >-
    git submodule update --init --recursive

    nuget restore OverwatchToolchain.sln
build:
  project: OverwatchToolchain.sln
  verbosity: minimal
branches:
  only:
  - master
before_package:
- cmd: >-
    del /F /Q dist\Release\*.pdb

    del /F /Q dist\Release\*.xml

    del /F /Q TankView\bin\Release\*.pdb

    del /F /Q TankView\bin\Release\*.xml
artifacts:
- path: dist/Release
  name: toolchain-release
- path: dist/Release/TACTLib.dll
  name: TACTLib
- path: dist/Release/TankLib.dll
  name: TankLib
- path: TankView/bin/Release
  name: TankView
cache:
  - packages -> **\packages.config 
