// Instance generated by TankLibHelper.InstanceBuilder

using System.Collections.Generic;
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x2F33B1B7)]
    public class STU_2F33B1B7 : STUInstance {
        [STUFieldAttribute(0xA20DCD80)]
        public ulong m_A20DCD80;

        [STUFieldAttribute(0x0619C597, "m_type")]
        public Enum_1AA009C2 m_type;

        [STUFieldAttribute(0x967A138B)]
        public Enum_AB6CE3D1 m_967A138B;

        [STUFieldAttribute(0x07D0F7AA)]
        public int m_07D0F7AA;
        
        public string GetCelebrationType(ulong key) {
            CelebrationMapping.TryGetValue(key, out string celeb);
            return celeb ?? $"UNKNOWN CELEBRATION? {teResourceGUID.AsString(key)}";
        }

        public static readonly Dictionary<ulong, string> CelebrationMapping = new Dictionary<ulong, string> {
            // 01C
            {0xD80000000002498, "Lunar New Year"},
            {0xD80000000002497, "New Years Resolution"},
            {0xD80000000002168, "Christmas"},
            {0xD8000000000212E, "Halloween"},
            {0xD800000000024A6, "Valentines Day"},
            {0xD80000000002658, "St. Patricks Day"},
            // 0C3, not too sure how these are different to the ones above
            {0x430000000000029, "Halloween"},
            {0x430000000000013, "New Years Resolution"}
        };
    }
}
