// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

using System.Collections.Generic;

namespace TankLib.STU.Types {
    [STUAttribute(0xC37857A5)]
    public class STU_C37857A5 : STU_2F33B1B7 {
        [STUFieldAttribute(0xED999C8B, "m_celebrationType")]
        public teStructuredDataAssetRef<STUIdentifier> m_celebrationType;

        public string GetCelebrationType(ulong key) {
            CelebrationMapping.TryGetValue(key, out string celeb);
            return celeb ?? $"UNKNOWN CELEBRATION? {teResourceGUID.AsString(key)}";
        }

        public static readonly Dictionary<ulong, string> CelebrationMapping = new Dictionary<ulong, string> {
            {0xD80000000002498, "Lunar New Year"},
            {0xD80000000002497, "New Years Resolution"},
            {0xD80000000002168, "Christmas"},
            {0xD8000000000212E, "Halloween"},
            {0xD800000000024A6, "Valentines Day"},
            {0xD80000000002658, "St. Patricks Day"}
        };
    }
}
